/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomType = IDL.Variant({
  'sharedRoom' : IDL.Null,
  'single' : IDL.Null,
});
export const AvailabilityStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'available' : IDL.Null,
});
export const RoomListing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'contactInfo' : IDL.Text,
  'rentAmount' : IDL.Nat,
  'amenities' : IDL.Vec(IDL.Text),
  'availability' : AvailabilityStatus,
  'roomType' : RoomType,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addRoomListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        RoomType,
        IDL.Vec(IDL.Text),
        IDL.Text,
        AvailabilityStatus,
      ],
      [],
      [],
    ),
  'getAllAvailableRooms' : IDL.Func([], [IDL.Vec(RoomListing)], ['query']),
  'getAllRooms' : IDL.Func([], [IDL.Vec(RoomListing)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomType = IDL.Variant({
    'sharedRoom' : IDL.Null,
    'single' : IDL.Null,
  });
  const AvailabilityStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'available' : IDL.Null,
  });
  const RoomListing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'contactInfo' : IDL.Text,
    'rentAmount' : IDL.Nat,
    'amenities' : IDL.Vec(IDL.Text),
    'availability' : AvailabilityStatus,
    'roomType' : RoomType,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addRoomListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          RoomType,
          IDL.Vec(IDL.Text),
          IDL.Text,
          AvailabilityStatus,
        ],
        [],
        [],
      ),
    'getAllAvailableRooms' : IDL.Func([], [IDL.Vec(RoomListing)], ['query']),
    'getAllRooms' : IDL.Func([], [IDL.Vec(RoomListing)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };