/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RoomType = IDL.Variant({
  'sharedRoom' : IDL.Null,
  'single' : IDL.Null,
});
export const AvailabilityStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'available' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const RoomListing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'contactInfo' : IDL.Text,
  'rentAmount' : IDL.Nat,
  'amenities' : IDL.Vec(IDL.Text),
  'availability' : AvailabilityStatus,
  'roomType' : RoomType,
  'location' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addRoomListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        RoomType,
        IDL.Vec(IDL.Text),
        IDL.Text,
        AvailabilityStatus,
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
  'getAllAvailableRooms' : IDL.Func([], [IDL.Vec(RoomListing)], ['query']),
  'getAllRooms' : IDL.Func([], [IDL.Vec(RoomListing)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RoomType = IDL.Variant({
    'sharedRoom' : IDL.Null,
    'single' : IDL.Null,
  });
  const AvailabilityStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'available' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const RoomListing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'contactInfo' : IDL.Text,
    'rentAmount' : IDL.Nat,
    'amenities' : IDL.Vec(IDL.Text),
    'availability' : AvailabilityStatus,
    'roomType' : RoomType,
    'location' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addRoomListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          RoomType,
          IDL.Vec(IDL.Text),
          IDL.Text,
          AvailabilityStatus,
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
    'getAllAvailableRooms' : IDL.Func([], [IDL.Vec(RoomListing)], ['query']),
    'getAllRooms' : IDL.Func([], [IDL.Vec(RoomListing)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };