/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AvailabilityStatus = { 'occupied' : null } |
  { 'available' : null };
export interface RoomListing {
  'id' : string,
  'title' : string,
  'contactInfo' : string,
  'rentAmount' : bigint,
  'amenities' : Array<string>,
  'availability' : AvailabilityStatus,
  'roomType' : RoomType,
  'location' : string,
}
export type RoomType = { 'sharedRoom' : null } |
  { 'single' : null };
export interface _SERVICE {
  'addRoomListing' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      RoomType,
      Array<string>,
      string,
      AvailabilityStatus,
    ],
    undefined
  >,
  'getAllAvailableRooms' : ActorMethod<[], Array<RoomListing>>,
  'getAllRooms' : ActorMethod<[], Array<RoomListing>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];